INSERT INTO indicator (id, question, area) VALUES
  ('001', 'Conseguimos fazer com que nossos jovens assumam seu próprio desenvolvimento e sejam responsáveis pelas decisões que tomam?', 'VALORES'),
  ('002', 'Nossos jovens expressam por ações seu gosto pela vida e sua disposição para conviver com os demais, valorizando igualmente a todas as pessoas?', 'VALORES'),
  ('003', 'Nossos jovens manifestam seu interesse pelo meio ambiente, participando de atividades voltadas para preservá-lo e melhorá-lo?', 'VALORES'),
  ('004', 'Jovens e adultos do grupo escoteiro integram sua fé religiosa à sua vida?', 'VALORES'),
  ('005', 'Nossos jovens compreendem a importância de ter uma só palavra?', 'VALORES'),
  ('006', 'Nosso grupo realiza atividades que possibilitem aos jovens o desenvolvimento e a valorização da lealdade?', 'VALORES'),
  ('007', 'Nossos jovens cativam aos demais pela sua cortesia e cordialidade?', 'VALORES'),
  ('008', 'Nossos jovens se esforçam para viver segundo os valores contidos na Lei e na Promessa?', 'VALORES'),
  ('009', 'No relacionamento dos nossos jovens com os demais, se percebe a limpeza de pensamentos, palavras e ações?', 'VALORES'),
  ('010', 'Promovemos, por meio da coeducação, a igualdade de direitos e o enriquecimento mútuo, respeitando as particularidades de cada sexo?', 'VALORES'),
  ('011', 'Escotistas e dirigentes dão testemunho dos valores escoteiros e, pela sua conduta, convidam a viver segundo esses valores?', 'VALORES'),
  ('012', 'As reuniões de diretoria e do Conselho de Dirigentes e Escotistas constituem oportunidades para o desenvolvimento de valores?', 'VALORES'),
  ('013', 'As atividades realizadas pelas seções contribuem para que os jovens adquiram competências em todas as áreas de desenvolvimento (físico, intelectual, social, afetivo, espiritual e do caráter)?', 'PROGRAMA_EDUCATIVO'),
  ('014', 'Nossas atividades dão oportunidades para que os jovens vivenciem os valores da Lei e da Promessa?', 'PROGRAMA_EDUCATIVO'),
  ('015', 'A vida em grupo em nossas seções evidencia a aplicação de todos os seguintes elementos do método escoteiro: suporte do adulto, sistema de equipes, marco simbólico, aprender fazendo?', 'PROGRAMA_EDUCATIVO'),
  ('016', 'As equipes/patrulhas conservam sua identidade e realizam atividades independentes das das seções?', 'PROGRAMA_EDUCATIVO'),
  ('017', 'Pelo menos 50% das ideias exploradas em atividades são fornecidas pelos jovens?', 'PROGRAMA_EDUCATIVO'),
  ('018', 'Os jovens alcançam, em média, a conclusão de uma etapa de progressão a cada ano de permanência?', 'PROGRAMA_EDUCATIVO'),
  ('020', 'Os marcos simbólicos de cada ramo são corretamente explorados nas seções correspondentes?', 'PROGRAMA_EDUCATIVO'),
  ('021', 'Os jovens conquistam, pelo menos, três especialidades em cada ramo?', 'PROGRAMA_EDUCATIVO'),
  ('022', 'Entre os jogos aplicados anualmente em cada seção, pelo menos vinte são jogos novos?', 'PROGRAMA_EDUCATIVO'),
  ('023', 'Os membros juvenis aprendem, a cada ano, um mínimo de vinte novas canções?', 'PROGRAMA_EDUCATIVO'),
  ('024', 'Os membros juvenis participam, anualmente, de um mínimo de 4 lamparadas, fogos de conselho ou alguma outra atividade que possibilite a expressão artística?', 'PROGRAMA_EDUCATIVO'),
  ('025', 'Os membros juvenis participam de uma atividade semanal de reflexão, apropriada à sua idade?', 'PROGRAMA_EDUCATIVO'),
  ('026', 'As orações e outras expressões de vida espiritual se integram adequadamente às nossas atividades?', 'PROGRAMA_EDUCATIVO'),
  ('027', 'Os ciclos de programa das seções incluem excursões e acampamentos decididos pelos jovens, e se observa superação na sua preparação, montagem e realização?', 'PROGRAMA_EDUCATIVO'),
  ('028', 'O ramo Lobinho acantonou um mínimo de seis noites durante o ano?', 'PROGRAMA_EDUCATIVO'),
  ('029', 'Os ramos Escoteiro e Sênior passaram um mínimo de dez noites em acampamento durante o ano?', 'PROGRAMA_EDUCATIVO'),
  ('030', 'O ramo Pioneiro dedicou um mínimo de quinze dias, ao longo do ano, a atividades de desenvolvimento sociocultural?', 'PROGRAMA_EDUCATIVO'),
  ('031', 'As seções procuram motivar os membros juvenis à conquista das insígnias de interesse especial?', 'PROGRAMA_EDUCATIVO'),
  ('032', 'Nossos jovens se integram à comunidade por meio de ações de serviço e/ou desenvolvimento?', 'PROGRAMA_EDUCATIVO'),
  ('033', 'As seções têm conseguido integrar jovens carentes, mesmo não se situando o grupo em área com essa característica?', 'PROGRAMA_EDUCATIVO'),
  ('034', 'As seções têm conseguido integrar jovens com deficiências?', 'PROGRAMA_EDUCATIVO'),
  ('035', 'As seções paralelas de um mesmo ramo realizam, pelo menos, uma atividade mensal de natureza coeducativa?', 'PROGRAMA_EDUCATIVO'),
  ('036', 'A educação para o relacionamento afetivo de ambos os sexos se faz presente em uma atividade mensal de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('037', 'A educação para a paz é tema de, pelo menos, duas atividades anuais de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('038', 'A educação para o desenvolvimento é tema de, pelo menos, duas atividades anuais de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('039', 'A educação para a democracia é tema de, pelo menos, duas atividades anuais de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('040', 'Os ramos Pioneiro e Sênior dedicam duas atividades anuais ao descobrimento e à orientação vocacional?', 'PROGRAMA_EDUCATIVO'),
  ('041', 'A fraternidade mundial e a compreensão intercultural são temas de, pelo menos, uma atividade anual de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('042', 'As atividades das seções ocorrem conforme o planejamento, sem atrasos ou ausências de escotistas?', 'PROGRAMA_EDUCATIVO'),
  ('043', 'Cada atividade conta com a participação de, pelo menos, 80% do efetivo de cada seção?', 'PROGRAMA_EDUCATIVO'),
  ('044', 'Os membros juvenis participam ativamente dos diversos órgãos que eles integram (ex.: Conselho de Patrulha, Assembleia de Tropa, Corte de Honra), de acordo com o método escoteiro?', 'PROGRAMA_EDUCATIVO'),
  ('045', 'As ações se regem pelas decisões dos órgãos juvenis competentes (ex.: Assembleia de Tropa), de acordo com o método escoteiro?', 'PROGRAMA_EDUCATIVO'),
  ('046', 'As seções do grupo escoteiro elaboram seus calendários de atividades com a participação de seus jovens e utilizam o ciclo de programa?', 'PROGRAMA_EDUCATIVO'),
  ('048', 'Todos os jovens têm oportunidade de exercitar a liderança?', 'PROGRAMA_EDUCATIVO'),
  ('049', 'As seções conservam atualizados os registros que permitam avaliar o seu desenvolvimento (frequência, acompanhamento das competências, atividades, fichas 120 e outros)?', 'PROGRAMA_EDUCATIVO'),
  ('050', 'As competências adquiridas pelos jovens são adequadamente avaliadas e reconhecidas?', 'PROGRAMA_EDUCATIVO'),
  ('051', 'Os escotistas se apresentam corretamente trajados?', 'PROGRAMA_EDUCATIVO'),
  ('052', 'Os membros juvenis se apresentam corretamente trajados?', 'PROGRAMA_EDUCATIVO'),
  ('053', 'Os escotistas se integram ao dinamismo juvenil das atividades, sem atitudes infantis, escapistas ou autoritárias?', 'PROGRAMA_EDUCATIVO'),
  ('054', 'Os membros juvenis permanecem ligados ao Movimento por um prazo não inferior a seis anos?', 'PROGRAMA_EDUCATIVO'),
  ('055', 'O grupo costuma realizar uma atividade semestral de todo o grupo?', 'PROGRAMA_EDUCATIVO'),
  ('056', 'As tradições mantidas pelo grupo reforçam os valores do Movimento e motivam nos jovens o orgulho de integrá-lo?', 'PROGRAMA_EDUCATIVO'),
  ('058', 'O grupo incentiva a atuação dos membros juvenis em outras organizações culturais, religiosas, esportivas, sociais ou políticas?', 'PROGRAMA_EDUCATIVO'),
  ('059', 'As atividades se desenvolvem sob rigorosas condições de segurança?', 'PROGRAMA_EDUCATIVO'),
  ('060', 'Os adultos do grupo, compreendendo a diretoria e o Conselho de Dirigentes e Escotistas, formam um ponto de encontro de diferentes gerações em que se integram harmoniosamente indivíduos de idades variadas?', 'RECURSOS_HUMANOS'),
  ('061', 'Todos os chefes em atuação no ramo Lobinho têm mais de 18 anos de idade?', 'RECURSOS_HUMANOS'),
  ('062', 'Todos os chefes em atuação no ramo Escoteiro têm mais de 21 anos de idade?', 'RECURSOS_HUMANOS'),
  ('063', 'Todos os chefes dos ramos Sênior e Pioneiro, assim como o Diretor de Métodos Educativos, têm mais de 25 anos de idade?', 'RECURSOS_HUMANOS'),
  ('064', 'A chefia e a diretoria são integradas por ex-membros juvenis do grupo e por adultos da comunidade com que o grupo se relaciona?', 'RECURSOS_HUMANOS'),
  ('065', 'Os dirigentes e escotistas do grupo cursaram o Ensino Médio e possuem formação cultural adequada para a função que desempenham?', 'RECURSOS_HUMANOS'),
  ('066', 'O grupo escoteiro consegue captar adultos para atender às próprias necessidades e de acordo com o perfil indicado para o exercício de cada função?', 'RECURSOS_HUMANOS'),
  ('067', 'O grupo estimula pais, antigos membros juvenis e membros da entidade patrocinadora a assumir funções como escotistas e dirigentes?', 'RECURSOS_HUMANOS'),
  ('069', 'Os adultos estão procurando obter melhor qualificação para o exercício de suas funções, de acordo com o previsto em seu plano pessoal de formação?', 'RECURSOS_HUMANOS'),
  ('072', 'O grupo conta com, pelo menos, um escotista portador da Insígnia de Madeira?', 'RECURSOS_HUMANOS'),
  ('073', 'Os dirigentes do grupo participam de cursos específicos da linha de formação de dirigentes institucionais?', 'RECURSOS_HUMANOS'),
  ('074', 'Existe, no grupo, pelo menos um escotista que integre alguma EQUIPE regional?', 'RECURSOS_HUMANOS'),
  ('075', 'Os chefes de seção permanecem em suas funções por períodos de 3 a 6 anos?', 'RECURSOS_HUMANOS'),
  ('076', 'Cada vez que um adulto assume uma função, o grupo formaliza com ele um compromisso mútuo por um prazo determinado?', 'RECURSOS_HUMANOS'),
  ('077', 'O grupo escoteiro proporciona aos adultos o apoio necessário para o exercício da função e avalia o desempenho de cada um deles?', 'RECURSOS_HUMANOS'),
  ('078', 'Os escotistas e dirigentes do grupo são motivados a participar em jornadas de capacitação/aperfeiçoamento organizadas pela direção distrital/regional/nacional?', 'RECURSOS_HUMANOS'),
  ('080', 'O grupo presta seu reconhecimento a escotistas e dirigentes que se destacam pela sua dedicação, propondo seus nomes para a concessão de diplomas e medalhas?', 'RECURSOS_HUMANOS'),
  ('081', 'Adultos que não estejam sendo aproveitados no grupo são estimulados e orientados na abertura de novos grupos escoteiros?', 'RECURSOS_HUMANOS'),
  ('082', 'Escotistas e dirigentes que se revelam inadequados são aconselhados, de maneira apropriada, a deixarem suas funções?', 'RECURSOS_HUMANOS'),
  ('083', 'O crescimento pessoal dos adultos é estimulado por meio do incentivo ao cumprimento de suas responsabilidades familiares, profissionais, estudantis e sociais?', 'RECURSOS_HUMANOS'),
  ('084', 'O grupo realiza, pelo menos uma vez a cada ano, atividades que auxiliem os pais na tarefa de atuarem como os principais educadores dos seus filhos?', 'RECURSOS_HUMANOS'),
  ('085', 'Os dirigentes conhecem a legislação escoteira em vigor?', 'GESTAO'),
  ('086', 'A diretoria se reúne periodicamente e cumpre as funções de coordenação das seções, administração do grupo e desenvolvimento pessoal dos adultos?', 'GESTAO'),
  ('087', 'O Diretor de Métodos Educativos e os demais dirigentes são substituídos ao término do mandato da diretoria?', 'GESTAO'),
  ('088', 'Existe alguém designado especialmente para acompanhar a execução do Plano de Grupo, liberando o Diretor-Presidente e o Diretor de Métodos Educativos para que cumpram as demais tarefas imediatas de coordenação?', 'GESTAO'),
  ('089', 'As passagens de funções se fazem acompanhar da entrega ordenada da documentação pertinente?', 'GESTAO'),
  ('090', 'Os Conselhos de Pais das seções se reúnem, pelo menos, duas vezes a cada ano?', 'GESTAO'),
  ('091', 'Representantes dos pais são convidados a participar das reuniões de diretoria ou do Conselho de Dirigentes e Escotistas?', 'GESTAO'),
  ('092', 'Os pais desenvolvem as funções educativas e as tarefas administrativas que cabem a eles na vida do Grupo?', 'GESTAO'),
  ('094', 'Os pais são informados, por escrito, das principais atividades desenvolvidas pelo grupo?', 'GESTAO'),
  ('096', 'O grupo escoteiro se relaciona ativamente com a instituição patrocinadora e com os organismos e autoridades da comunidade local?', 'GESTAO'),
  ('097', 'Os membros juvenis tomam parte das atividades desenvolvidas pela entidade patrocinadora, quando se solicita sua colaboração?', 'GESTAO'),
  ('098', 'Os adultos do grupo dispõem de um local exclusivo para suas reuniões e para guarda de arquivos e outros documentos?', 'GESTAO'),
  ('099', 'As seções dispõem de espaço físico adequado para suas atividades e reuniões?', 'GESTAO'),
  ('100', 'O grupo conta com uma biblioteca ou centro de documentação para consulta dos escotistas e dirigentes, bem como dos jovens?', 'GESTAO'),
  ('101', 'As seções dispõem de instalações, material e equipamento em quantidade e qualidade adequada às suas atividades?', 'GESTAO'),
  ('102', 'As instalações, o material e o equipamento são mantidos limpos, seguros e em bom estado de conservação?', 'GESTAO'),
  ('104', 'O grupo mantém sistema adequado de informação (livros-ata, fichas individuais...)?', 'GESTAO'),
  ('105', 'Existe no grupo um sistema rápido e eficaz de comunicações internas?', 'GESTAO'),
  ('106', 'As informações dirigidas aos escotistas, dirigentes, pais, autoridades da comunidade, da Região e do nível Nacional circulam de maneira apropriada?', 'GESTAO'),
  ('107', 'O grupo responde tempestivamente às consultas formuladas pelos diversos níveis de direção do Movimento?', 'GESTAO'),
  ('108', 'O grupo registra seu efetivo de maneira completa e oportuna? Tem uma participação efetiva na vida e nas atividades regionais e nacionais?', 'GESTAO'),
  ('109', 'O grupo mantém em funcionamento um Círculo de Antigos Escoteiros ou um Clube da Flor de Lis?', 'GESTAO'),
  ('110', 'O grupo organiza, periodicamente, atividades de divulgação do escotismo?', 'GESTAO'),
  ('111', 'O grupo se coloca à disposição das autoridades comunitárias para prestar serviços?', 'GESTAO'),
  ('113', 'O grupo participa das reuniões dos órgãos de direção distrital, regional e nacional do Movimento Escoteiro?', 'GESTAO'),
  ('114', 'O grupo estimula seus escotistas e dirigentes a aceitarem cargos em outros níveis do Movimento?', 'GESTAO'),
  ('115', 'A diretoria de grupo conta com recursos humanos adequados para apoiar a gestão financeira do grupo?', 'FINANCAS'),
  ('116', 'O grupo elabora um orçamento para fazer frente às ações previstas no Plano de Grupo? E limita suas despesas ao que consta do orçamento?', 'FINANCAS'),
  ('118', 'Os arquivos e a escrituração do grupo - inventários, comprovantes de receita e despesa, prestações de contas, etc. - são mantidos em dia?', 'FINANCAS'),
  ('119', 'Os comprovantes de receita e despesa são arquivados ordenadamente?', 'FINANCAS'),
  ('121', 'As seções contam com suprimento de fundos para despesas imediatas?', 'FINANCAS'),
  ('122', 'O grupo mantém seus fundos em conta corrente ou poupança exclusiva e bipessoal?', 'FINANCAS'),
  ('123', 'O balanço anual, com cópia do inventário, é distribuído aos membros da Assembleia de Grupo e à entidade patrocinadora?', 'FINANCAS'),
  ('124', 'O grupo obtém recursos financeiros, por meio de diversas fontes de receita, suficientes para custear as ações incluídas no Plano de Grupo?', 'FINANCAS'),
  ('125', 'O grupo destina parcela das receitas à formação de recursos humanos?', 'FINANCAS'),
  ('126', 'O grupo tem, pelo menos, uma seção de cada ramo?', 'CRESCIMENTO'),
  ('127', 'As seções de todos os ramos têm o tamanho apropriado e contam com um número suficiente de escotistas? Como consequência das ações previstas neste plano, o grupo elaborou um programa de crescimento do número de jovens e adultos?', 'CRESCIMENTO'),
  ('130', 'O Diretor de Métodos Educativos se dedica apenas à sua função específica, sem acumular a chefia de nenhuma seção?', 'CRESCIMENTO');