export * from "./acaoRepository";
export * from "./acaoResponsavelRepository";
export * from "./diagnosticoRepository";
export * from "./indicadorRepository";
export * from "./metaAcaoRepository";
export * from "./metaRepository";
export * from "./ocorrenciaRepository";
export * from "./planoRepository";
export * from "./responsavelRepository";
